<?php

namespace AppBundle\Repository;

/**
 * TapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapaRepository extends \Doctrine\ORM\EntityRepository
{
    public function  paginaTapas($page=1){
        $numTapas=8;
        //Funcion que devuelve los posteos o tapas para una pagina con un numero de elementos
        $query = $this->createQueryBuilder('t')
            ->orderBy('t.fechaCreacion','DESC')
            ->setFirstResult($numTapas*($page-1))
            ->setMaxResults($numTapas)
            ->getQuery();
        return $query->getResult();
    }
}
